spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kdeploy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 7794306
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  http: 
    converters:
      preferred-json-mapper: fastjson
    encoding: 
      charset: UTF-8
      force-response: true
      
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
    
mapper:
    mappers: com.lk.kDeploy.base.BaseMapper
    not-empty: false
    identity: MYSQL
    
server:
  context-path: /kdeploy
  session:
    timeout: 1800
  port: 8880
  
kdeploy: 
  # 登录用户名
  username: admin
  # 登录密码
  password: 123123
  # 登录密码
  websocket: 
    # websocket监听地址，0.0.0.0就ok
    host: 0.0.0.0
    # websocket监听端口号
    port: 8881
  command:
    # 命令执行系统。linux, windows TODO
    system: windows
    # 命令执行回显字符串的编码，与系统有关。linux一般是UTF-8，笔者在windows开发故使用GBK
    system-charset: GBK
    # 命令执行超时时间，单位：分
    timeout: 2